"""2 db migration

Revision ID: 5c8de71d6bb5
Revises: 2c486a799e76
Create Date: 2021-04-22 21:31:56.431104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c8de71d6bb5'
down_revision = '2c486a799e76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'release_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'release_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
