"""3 db migration

Revision ID: a961bfab9b00
Revises: 5c8de71d6bb5
Create Date: 2021-04-22 21:42:51.727442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a961bfab9b00'
down_revision = '5c8de71d6bb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MovieActorDetails',
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], )
    )
    op.drop_table('movieactordetails')
    op.alter_column('movies', 'release_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'release_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_table('movieactordetails',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], name='movieactordetails_actor_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name='movieactordetails_movie_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='movieactordetails_pkey'),
    sa.UniqueConstraint('movie_id', 'actor_id', name='unique_constraint_movieactordetails')
    )
    op.drop_table('MovieActorDetails')
    # ### end Alembic commands ###
