CREATE DATABASE trivia;
CREATE DATABASE trivia_test;
CREATE USER caryn WITH ENCRYPTED PASSWORD 'caryn';
GRANT ALL PRIVILEGES ON DATABASE trivia TO caryn;
GRANT ALL PRIVILEGES ON DATABASE trivia_test TO caryn;
ALTER USER caryn CREATEDB;
ALTER USER caryn WITH SUPERUSER;